#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
AUTH_HOME="$SCRIPT_DIR/codex-home"
POLICY_HOME="$SCRIPT_DIR/codex-policy"
CONFIG_FILE="$POLICY_HOME/config.toml"
SANDBOX_POLICY_HOME="/opt/sandcastle-codex-policy"
CONFIG_LINK="$AUTH_HOME/config.toml"
CONFIG_LINK_TARGET="$SANDBOX_POLICY_HOME/config.toml"
LOCK_FILE="$SCRIPT_DIR/queue/autopilot.lock"
IMAGE_NAME="${SANDCASTLE_IMAGE:-meta-research-sandcastle:0.12.0}"
FORCE_LOGIN=0

if (( $# > 1 )); then
  printf 'Usage: npm run sandcastle:login [-- --force]\n' >&2
  exit 2
fi
if (( $# == 1 )); then
  if [[ "$1" != "--force" ]]; then
    printf 'Usage: npm run sandcastle:login [-- --force]\n' >&2
    exit 2
  fi
  FORCE_LOGIN=1
fi

fail() {
  warn "$1"
  exit 1
}

container_login_status() {
  docker run --rm \
    --network=none \
    --cap-drop=ALL \
    --security-opt no-new-privileges \
    --user "$(id -u):$(id -g)" \
    --env HOME=/home/agent \
    --env CODEX_HOME=/home/agent/.codex \
    --env CODEX_API_KEY= \
    --env CODEX_ACCESS_TOKEN= \
    --env OPENAI_API_KEY= \
    --volume "$AUTH_HOME:/home/agent/.codex:rw" \
    --volume "$POLICY_HOME:$SANDBOX_POLICY_HOME:ro" \
    --entrypoint codex \
    "$IMAGE_NAME" login status >/dev/null 2>&1
}

container_logout() {
  docker run --rm \
    --network=none \
    --cap-drop=ALL \
    --security-opt no-new-privileges \
    --user "$(id -u):$(id -g)" \
    --env HOME=/home/agent \
    --env CODEX_HOME=/home/agent/.codex \
    --env CODEX_API_KEY= \
    --env CODEX_ACCESS_TOKEN= \
    --env OPENAI_API_KEY= \
    --volume "$AUTH_HOME:/home/agent/.codex:rw" \
    --volume "$POLICY_HOME:$SANDBOX_POLICY_HOME:ro" \
    --entrypoint codex \
    "$IMAGE_NAME" logout >/dev/null 2>&1
}

mkdir -p "$(dirname "$LOCK_FILE")"
command -v flock >/dev/null 2>&1 || fail "flock is required by the Sandcastle controller."
exec 9>"$LOCK_FILE"
flock --exclusive --nonblock 9 || fail "Sandcastle autopilot is running; stop it before changing its login."

banner "Sandcastle Codex login"

stage "Prepare an isolated login cache"
say "The wizard isolates this runner's Codex login and runtime state under .sandcastle/codex-home."
command -v docker >/dev/null 2>&1 || fail "Docker is not installed or not on PATH."
docker image inspect "$IMAGE_NAME" >/dev/null 2>&1 || \
  fail "Docker image $IMAGE_NAME is missing; run npm run sandcastle:build-image first."
[[ -d "$POLICY_HOME" && ! -L "$POLICY_HOME" && -f "$CONFIG_FILE" && ! -L "$CONFIG_FILE" ]] || \
  fail "The versioned Codex sandbox config is missing or is a symlink."
git -C "$REPO_ROOT" check-ignore -q "$AUTH_HOME/auth.json" || \
  fail ".sandcastle/codex-home is not ignored by Git; refusing to create credentials."
grep -Fxq "codex-home/" "$SCRIPT_DIR/.dockerignore" || \
  fail ".sandcastle/codex-home is not excluded from the Docker build context."
[[ ! -L "$AUTH_HOME" ]] || fail "The dedicated Codex home must not be a symlink."
install -d -m 0700 "$AUTH_HOME"
chmod 0700 "$AUTH_HOME"
if [[ -d "$CONFIG_LINK" && ! -L "$CONFIG_LINK" ]]; then
  rmdir "$CONFIG_LINK" 2>/dev/null || \
    fail "Unexpected non-empty directory at $CONFIG_LINK; inspect it manually."
fi
if [[ -e "$CONFIG_LINK" || -L "$CONFIG_LINK" ]]; then
  [[ -L "$CONFIG_LINK" && "$(readlink "$CONFIG_LINK")" == "$CONFIG_LINK_TARGET" ]] || \
    fail "Existing config.toml is not the fixed sandbox-policy symlink."
else
  ln -s "$CONFIG_LINK_TARGET" "$CONFIG_LINK"
fi
if [[ -e "$AUTH_HOME/auth.json" || -L "$AUTH_HOME/auth.json" ]]; then
  [[ -f "$AUTH_HOME/auth.json" && ! -L "$AUTH_HOME/auth.json" ]] || \
    fail "Existing auth.json must be a regular file, not a symlink."
  [[ "$(stat -c '%u:%g' "$AUTH_HOME/auth.json")" == "$(id -u):$(id -g)" ]] || \
    fail "Existing auth.json is not owned by the controller UID:GID."
  chmod 0600 "$AUTH_HOME/auth.json"
fi
note "Prepared $AUTH_HOME with mode 0700."

stage "Sign in with your ChatGPT account"
say "Codex will print an official device-login URL and a one-time code."
step "Open that URL, choose the ChatGPT workspace you want Sandcastle to use, and enter the code."
if (( FORCE_LOGIN )); then
  [[ -t 0 && -t 1 ]] || \
    fail "--force needs an interactive terminal; the existing login was left unchanged."
  if [[ -f "$AUTH_HOME/auth.json" ]]; then
    say "--force was requested; signing the dedicated cache out before device login."
    container_logout || fail "Codex could not clear the dedicated login cache."
  fi
fi
if (( ! FORCE_LOGIN )) && container_login_status; then
  note "This dedicated cache is already signed in with ChatGPT; skipping login."
else
  [[ -t 0 && -t 1 ]] || fail "Device login needs an interactive terminal."
  docker run --rm --interactive --tty \
    --cap-drop=ALL \
    --security-opt no-new-privileges \
    --user "$(id -u):$(id -g)" \
    --env HOME=/home/agent \
    --env CODEX_HOME=/home/agent/.codex \
    --env CODEX_API_KEY= \
    --env CODEX_ACCESS_TOKEN= \
    --env OPENAI_API_KEY= \
    --volume "$AUTH_HOME:/home/agent/.codex:rw" \
    --volume "$POLICY_HOME:$SANDBOX_POLICY_HOME:ro" \
    --entrypoint codex \
    "$IMAGE_NAME" login --device-auth
fi
[[ -f "$AUTH_HOME/auth.json" && ! -L "$AUTH_HOME/auth.json" ]] || \
  fail "Codex did not create a regular auth.json file. Re-run this wizard."
[[ "$(stat -c '%u:%g' "$AUTH_HOME/auth.json")" == "$(id -u):$(id -g)" ]] || \
  fail "Codex auth.json is not owned by the controller UID:GID."
chmod 0600 "$AUTH_HOME/auth.json"

stage "Verify container reuse"
say "Checking the exact pinned image and mount layout used for every ticket."
container_login_status || \
  fail "The container could not reuse the dedicated ChatGPT login."
printf '  %s✓ verified%s dedicated ChatGPT login\n' "$GREEN" "$RESET"
note "No API key was created, copied, or added to .sandcastle/.env."

finish
say "Start with: npm run sandcastle:auto -- --dry-run"
say "Then run:   npm run sandcastle:auto"
