"""跨写入/消费边界共享的不可变安全上限。

这些值同时约束生产者写入/状态迁移和消费者编译；禁止在两侧各写一份数字，否则会重新引入
“合法接纳/消费后永久不可渲染”的楔死状态。
"""

MAX_FILE_REQUESTS_PER_GOAL = 5
MAX_REQUEST_ITEMS = 10
MAX_ASSETS_PER_GOAL = 512
MAX_CANCEL_REASON_CHARS = 2000
MAX_REASONING_DIRECTIVES_PER_CYCLE = 128
MAX_INFLIGHT_QUERY_CALLS = 4
MAX_QUEUED_QUERY_CALLS = 256
MAX_QUERY_HISTORY_TURNS = 100
MAX_QUERY_HISTORY_FIELD_CHARS = 512
MAX_QUERY_CURRENT_CHARS = 2_000
MAX_QUERY_CONTEXT_CHARS = 32_000
MAX_QUERY_STATUS_CARD_BYTES = 128 * 1024
